# Generated by Django 4.2 on 2023-04-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='process',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
