# Generated by Django 4.2 on 2023-04-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='about',
            field=models.TextField(default='This is a very easy to make recipe, that you can try whenever you are short on time and you need to cook something delicious for your loved ones', help_text='Short description about the recipe'),
            preserve_default=False,
        ),
    ]
