// auth

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const AUTHENTICATED_SUCCUESS = 'AUTHENTICATED_SUCCUESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const LOGOUT = 'LOGOUT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR'


// recipe

export const RECIPE_LOAD_SUCCESS = 'RECIPE_LOAD_SUCCESS';
export const RECIPE_LOAD_FAILURE = 'RECIPE_LOAD_FAILURE'
export const CHANGE_TAB_VALUE = 'CHANGE_TAB_VALUE'
export const MY_RECIPE_LOAD_SUCCESS = 'MY_RECIPE_LOAD_SUCCESS'
export const MY_RECIPE_LOAD_FAILURE = 'MY_RECIPE_LOAD_FAILURE'
export const RECIPE_DETAIL_LOAD_SUCCESS = 'RECIPE_DETAIL_LOAD_SUCCES'
export const RECIPE_DETAIL_LOAD_FAILURE = 'RECIPE_DETAIL_LOAD_FAILURE'
export const REVIEW_POST_SUCCESS = 'REVIEW_POST_SUCCESS'
export const REVIEW_POST_FAILURE = 'REVIEW_POST_FAILURE'
export const OPEN_RECIPE_MODAL = 'OPEN_RECIPE_MODAL'
export const CLOSE_RECIPE_MODAL = 'CLOSE_RECIPE_MODAL'
export const RECIPE_CREATION_SUCCESS = 'RECIPE_CREATION_SUCCESS'
export const RECIPE_CREATION_FAILURE = 'RECIPE_CREATION_FAILURE'
export const RESET_RECIPE_STATE = 'RESET_RECIPE_STATE'
